# Generated by Django 5.0.6 on 2024-06-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="blood_type",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                default="A",
                max_length=3,
            ),
        ),
    ]
