# Generated by Django 5.0.6 on 2024-06-28 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_caza"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="caza",
            field=models.CharField(
                choices=[
                    ("Rachaya", "Rachaya"),
                    ("Aley", "Aley"),
                    ("Baabda", "Baabda"),
                    ("Saida", "Saida"),
                    ("El Minieh-Dennie", "El Minieh-Dennie"),
                    ("Al Chouf", "Al Chouf"),
                    ("El Koura", "El Koura"),
                    ("Beirut", "Beirut"),
                    ("Kesseroune", "Kesseroune"),
                    ("El Meten", "El Meten"),
                    ("Akkar", "Akkar"),
                    ("Zahle", "Zahle"),
                    ("Tripoli", "Tripoli"),
                    ("Jbeil", "Jbeil"),
                    ("Zgharta", "Zgharta"),
                    ("El Nabatieh", "El Nabatieh"),
                    ("West Bekaa", "West Bekaa"),
                ],
                default="Beirut",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
