# Generated by Django 5.0.6 on 2024-06-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_caza_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="caza",
            field=models.CharField(
                choices=[
                    ("Aley", "Aley"),
                    ("El Koura", "El Koura"),
                    ("Al Chouf", "Al Chouf"),
                    ("El Minieh-Dennie", "El Minieh-Dennie"),
                    ("Saida", "Saida"),
                    ("West Bekaa", "West Bekaa"),
                    ("Tripoli", "Tripoli"),
                    ("El Meten", "El Meten"),
                    ("Beirut", "Beirut"),
                    ("Rachaya", "Rachaya"),
                    ("Jbeil", "Jbeil"),
                    ("Kesseroune", "Kesseroune"),
                    ("Akkar", "Akkar"),
                    ("Zahle", "Zahle"),
                    ("Baabda", "Baabda"),
                    ("Zgharta", "Zgharta"),
                    ("El Nabatieh", "El Nabatieh"),
                ],
                default="Beirut",
                max_length=25,
            ),
        ),
    ]
