# Generated by Django 5.0.6 on 2024-06-28 15:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        default="A+",
                        max_length=3,
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        choices=[
                            ("Ain Wzen Hospital", "Ain Wzen Hospital"),
                            ("Akkar Rahal Hospital", "Akkar Rahal Hospital"),
                            ("Al Hamshari Hospital", "Al Hamshari Hospital"),
                            ("Al Hayat Hospital", "Al Hayat Hospital"),
                            ("Al Hikme Hospital", "Al Hikme Hospital"),
                            ("Al Iman Hospital", "Al Iman Hospital"),
                            ("Al Jabal Hospital", "Al Jabal Hospital"),
                            (
                                "Al Kheir Hospital- Miniyeh",
                                "Al Kheir Hospital- Miniyeh",
                            ),
                            (
                                "Al Manara Doctors Hospital",
                                "Al Manara Doctors Hospital",
                            ),
                            ("Al Mounla Hospital", "Al Mounla Hospital"),
                            ("Al Rahban Hospital", "Al Rahban Hospital"),
                            ("Al Rahma Hospital", "Al Rahma Hospital"),
                            ("AL Salam Hospital", "AL Salam Hospital"),
                            ("Al Watani Hospital", "Al Watani Hospital"),
                            ("Al-Hanan Hospital", "Al-Hanan Hospital"),
                            (
                                "Al-Rasoul Al-Aazam Hospital",
                                "Al-Rasoul Al-Aazam Hospital",
                            ),
                            (
                                "Al-Zahraa Hospital University Medical Center",
                                "Al-Zahraa Hospital University Medical Center",
                            ),
                            ("Alaa-El-Dine Hospital", "Alaa-El-Dine Hospital"),
                            ("AlCheick Harb Hospital", "AlCheick Harb Hospital"),
                            ("Alerfan Hospital", "Alerfan Hospital"),
                            (
                                "Alhamid Medical Center-Ghandour Hospital",
                                "Alhamid Medical Center-Ghandour Hospital",
                            ),
                            ("Aljanoub Hospital", "Aljanoub Hospital"),
                            ("Alraai Hospital", "Alraai Hospital"),
                            (
                                "American University of Beirut Medical Center",
                                "American University of Beirut Medical Center",
                            ),
                            ("Arz Hospital", "Arz Hospital"),
                            ("Azounieh Hospital", "Azounieh Hospital"),
                            ("BaakleenHospital", "BaakleenHospital"),
                            (
                                "Bahmad & el-fakih Hospital",
                                "Bahmad & el-fakih Hospital",
                            ),
                            ("Bahman Hospital", "Bahman Hospital"),
                            (
                                "Bchamoun Speciality Hospital",
                                "Bchamoun Speciality Hospital",
                            ),
                            (
                                "Beirut Eye Specialist Hospital",
                                "Beirut Eye Specialist Hospital",
                            ),
                            ("Beirut General Hospital", "Beirut General Hospital"),
                            ("Bekaa Hospital", "Bekaa Hospital"),
                            ("Bekhaazi Hospital", "Bekhaazi Hospital"),
                            ("Belle Vue Hopital", "Belle Vue Hopital"),
                            ("Borj Hospital", "Borj Hospital"),
                            (
                                "Centre Hopital de Behannss",
                                "Centre Hopital de Behannss",
                            ),
                            (
                                "Centre Hospitalier du Nord",
                                "Centre Hospitalier du Nord",
                            ),
                            (
                                "Child & Mother Welfare Society",
                                "Child & Mother Welfare Society",
                            ),
                            ("Chtoura Hospital", "Chtoura Hospital"),
                            (
                                "CHU Notre Dame de Secours Hospital",
                                "CHU Notre Dame de Secours Hospital",
                            ),
                            ("Clemenceau Medical Center", "Clemenceau Medical Center"),
                            (
                                "Clinique DE Chirugie Estetque Dr Nader Saab",
                                "Clinique DE Chirugie Estetque Dr Nader Saab",
                            ),
                            (
                                "Clinique Dr. Georges Moarbes",
                                "Clinique Dr. Georges Moarbes",
                            ),
                            ("Clinique du Levant SM", "Clinique du Levant SM"),
                            ("Dalaa Hospital", "Dalaa Hospital"),
                            ("Dar Al shifa hospital", "Dar Al shifa hospital"),
                            ("Dar Al Zahraa Hospital", "Dar Al Zahraa Hospital"),
                            (
                                "Dar Al-Ajaza Al-Islamia Hospital",
                                "Dar Al-Ajaza Al-Islamia Hospital",
                            ),
                            ("Dr Hamed Farhat Hospital", "Dr Hamed Farhat Hospital"),
                            ("Ehden Hospital", "Ehden Hospital"),
                            ("El Bissar Hospital", "El Bissar Hospital"),
                            (
                                "El Youssef Hospital Center",
                                "El Youssef Hospital Center",
                            ),
                            (
                                "Eye & Ear Hospital International",
                                "Eye & Ear Hospital International",
                            ),
                            (
                                "Fouad Khoury Hospital & Associates S.A.L.",
                                "Fouad Khoury Hospital & Associates S.A.L.",
                            ),
                            ("Ghossein Hospital", "Ghossein Hospital"),
                            (
                                "Hammoud Hospital University Medical Center",
                                "Hammoud Hospital University Medical Center",
                            ),
                            ("Haroun Hospital", "Haroun Hospital"),
                            (
                                "Health Medical Center- Osseiran Hospital",
                                "Health Medical Center- Osseiran Hospital",
                            ),
                            ("Hopital Beit Chabab", "Hopital Beit Chabab"),
                            ("Hopital Abou Jaouke", "Hopital Abou Jaouke"),
                            ("Hopital Al Borgi", "Hopital Al Borgi"),
                            ("Hopital Al Koura", "Hopital Al Koura"),
                            ("Hopital Albert Haykel sal", "Hopital Albert Haykel sal"),
                            ("Hopital DAR AL Raheme?", "Hopital DAR AL Raheme?"),
                            (
                                "Hopital Dr Toni Nassar Sal",
                                "Hopital Dr Toni Nassar Sal",
                            ),
                            (
                                "Hopital Francais - St Lourdes",
                                "Hopital Francais - St Lourdes",
                            ),
                            ("Hopital Hayek", "Hopital Hayek"),
                            ("Hopital Maritime Jbeil", "Hopital Maritime Jbeil"),
                            (
                                "Hopital Notre Dame de la Paix",
                                "Hopital Notre Dame de la Paix",
                            ),
                            (
                                "Hopital Notre dame pour les Malade Cronique",
                                "Hopital Notre dame pour les Malade Cronique",
                            ),
                            ("Hopital Saint Charles", "Hopital Saint Charles"),
                            (
                                "Hopital Saint- Michel Amchit",
                                "Hopital Saint- Michel Amchit",
                            ),
                            ("Hospital Almarkazi", "Hospital Almarkazi"),
                            ("Hospital al Hajj", "Hospital al Hajj"),
                            ("Hospital MGR Cortbawi", "Hospital MGR Cortbawi"),
                            ("Hospital Saydet Zgharta", "Hospital Saydet Zgharta"),
                            ("Hotel Dieu Hospital", "Hotel Dieu Hospital"),
                            ("Islamic Hospital", "Islamic Hospital"),
                            ("Jeatawi Hospital", "Jeatawi Hospital"),
                            ("Kalout Hospital", "Kalout Hospital"),
                            ("Kassab Hospital", "Kassab Hospital"),
                            ("Kesserwan Medical Center", "Kesserwan Medical Center"),
                            ("Kharroubi Hospital", "Kharroubi Hospital"),
                            ("Khoury General Hospital", "Khoury General Hospital"),
                            (
                                "Lebanese Ophthalmic Hospital",
                                "Lebanese Ophthalmic Hospital",
                            ),
                            (
                                "Lebanise--Canadian Hospital",
                                "Lebanise--Canadian Hospital",
                            ),
                            ("Libano-Francais Hospital", "Libano-Francais Hospital"),
                            ("Makasid Hospital", "Makasid Hospital"),
                            ("Medical 2000 Hospital", "Medical 2000 Hospital"),
                            (
                                "Middle East Institutd Of Health",
                                "Middle East Institutd Of Health",
                            ),
                            ("Miniyeh Hospital", "Miniyeh Hospital"),
                            ("Mount Lebanon Hospital", "Mount Lebanon Hospital"),
                            ("Najjar Hospital", "Najjar Hospital"),
                            ("New Mazloum Hospital", "New Mazloum Hospital"),
                            ("Nine Hospital", "Nine Hospital"),
                            (
                                "Notre Dame de Liban Hospital",
                                "Notre Dame de Liban Hospital",
                            ),
                            ("Osman Hospital", "Osman Hospital"),
                            (
                                "Palestinian Red Crescent Society Nazareth Hospital",
                                "Palestinian Red Crescent Society Nazareth Hospital",
                            ),
                            (
                                "Psychiatric Hospital of the Cross",
                                "Psychiatric Hospital of the Cross",
                            ),
                            ("Rayak Hospital", "Rayak Hospital"),
                            ("Rosaire Hospital", "Rosaire Hospital"),
                            (
                                "SACH Medical Co.Bitar Hospital",
                                "SACH Medical Co.Bitar Hospital",
                            ),
                            ("Sacre Coeur Hospital", "Sacre Coeur Hospital"),
                            ("Sahel General Hospital", "Sahel General Hospital"),
                            (
                                "Saint George Hospital University Medical Center",
                                "Saint George Hospital University Medical Center",
                            ),
                            ("Saint Joseph Hospital", "Saint Joseph Hospital"),
                            ("Sainte Therese Hospital", "Sainte Therese Hospital"),
                            (
                                "Secours Populaire Hospital",
                                "Secours Populaire Hospital",
                            ),
                            ("Serhal Hospital", "Serhal Hospital"),
                            ("Shahin Hospital", "Shahin Hospital"),
                            (
                                "Social Services Association - Dar Al Ajaza Hospice",
                                "Social Services Association - Dar Al Ajaza Hospice",
                            ),
                            (
                                "Specialized Hospital Haidar and Hajjar",
                                "Specialized Hospital Haidar and Hajjar",
                            ),
                            (
                                "Specialized Medical Rehabilitation Hospital",
                                "Specialized Medical Rehabilitation Hospital",
                            ),
                            (
                                "St Georges Hadath Hospital",
                                "St Georges Hadath Hospital",
                            ),
                            ("St Georges Hospital", "St Georges Hospital"),
                            ("St Louis Hospital", "St Louis Hospital"),
                            ("Taanayel General Hospital", "Taanayel General Hospital"),
                            ("Tal Chiha Hospital", "Tal Chiha Hospital"),
                            ("Trad Hospital", "Trad Hospital"),
                            (
                                "University Medical Center - Rizk Hospital",
                                "University Medical Center - Rizk Hospital",
                            ),
                            ("West Bekaa Hospital", "West Bekaa Hospital"),
                        ],
                        default="American University of Beirut Medical Center",
                        max_length=150,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
