# Generated by Django 5.0.6 on 2024-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_date_added_post_fullfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
